"""
seed_trips.py — Inserts 8 high quality demo trips into Supabase.
Run once from the server directory with venv activated:
    python seed_trips.py

Trips cover all 4 intent groups with 2 trips each.
Each trip gets auto-generated slug and sample reviews.
image_keywords generated by the image agent for each trip.
"""

import os
import sys
import json
import uuid
import re
import time
from dotenv import load_dotenv

sys.path.append(os.getcwd())
load_dotenv()

from supabase import create_client
from agents.image_agent import run_image_agent

# Initialize Supabase with service role key
supabase = create_client(
    os.environ["SUPABASE_URL"],
    os.environ["SUPABASE_SERVICE_ROLE_KEY"]
)

# ─────────────────────────────────────────────
# 8 DEMO TRIPS — 2 per intent group
# ─────────────────────────────────────────────

DEMO_TRIPS = [
    # ── Group 1: High-Energy & Stimulation ──
    {
        "intent": "Adrenaline",
        "intent_group": "High-Energy & Stimulation",
        "trip_data": {
            "title": "The Roof of the World",
            "destination": "Leh Ladakh",
            "country": "India",
            "duration_days": 8,
            "best_season": "June to September",
            "summary": "Barren moonscapes, oxygen-thin passes at 18,000 feet, and monasteries that cling to cliffs like they are defying gravity. Leh Ladakh does not just challenge your body — it rewires your perspective entirely.",
            "days": [
                {"day": 1, "location": "Leh City", "theme": "Acclimatisation", "activities": ["Explore Leh Palace", "Walk through Leh Market", "Rest and hydrate"], "accommodation": "Boutique guesthouse in Leh old town", "food": "Thukpa noodle soup at Tibetan Kitchen"},
                {"day": 2, "location": "Magnetic Hill & Sangam", "theme": "Orientation", "activities": ["Visit Magnetic Hill", "Confluence of Indus and Zanskar rivers", "Gurudwara Pathar Sahib"], "accommodation": "Leh guesthouse", "food": "Skyu traditional lamb stew"},
                {"day": 3, "location": "Nubra Valley", "theme": "Desert Dunes", "activities": ["Cross Khardung La pass 18379 ft", "Bactrian camel ride on Hunder sand dunes", "Diskit Monastery visit"], "accommodation": "Eco-camp in Hunder", "food": "Local dal and rice at camp"},
                {"day": 4, "location": "Pangong Lake", "theme": "The Blue Mirror", "activities": ["Drive to Pangong Tso", "Watch lake colour shift from blue to green to red", "Sunrise photography at 4am"], "accommodation": "Lakeside camp at Pangong", "food": "Instant noodles and chai at lakeside dhaba"},
                {"day": 5, "location": "Tso Moriri", "theme": "Wilderness", "activities": ["Drive through Changthang plateau", "Spot wild kiangs and bharals", "Visit nomadic Changpa settlements"], "accommodation": "Tso Moriri campsite", "food": "Butter tea and tsampa with Changpa nomads"},
                {"day": 6, "location": "Hemis & Thiksey", "theme": "Monasteries", "activities": ["Hemis Monastery treasure tour", "Thiksey monastery sunrise puja", "Shey Palace ruins"], "accommodation": "Leh heritage hotel", "food": "Momos at a local monastery cafe"},
                {"day": 7, "location": "Zanskar River", "theme": "White Water", "activities": ["Grade 4 river rafting on Zanskar", "Chadar frozen river trail edge walk", "Phugtal Monastery viewpoint"], "accommodation": "Kargil transit hotel", "food": "Wazwan feast with local Kargil family"},
                {"day": 8, "location": "Leh Departure", "theme": "Reflection", "activities": ["Early morning Shanti Stupa meditation", "Final market shopping for Pashmina", "Departure from Leh airport"], "accommodation": "Airport transit", "food": "Breakfast at Bon Appetit Leh"}
            ],
            "packing_tips": ["Carry Diamox for altitude sickness", "Layer clothing — mornings are freezing even in July", "Download offline maps — no signal in many areas", "Carry cash — ATMs frequently out of service"],
            "estimated_budget": "₹45,000 - ₹75,000 per person excluding flights from Delhi"
        }
    },
    {
        "intent": "Discovery",
        "intent_group": "High-Energy & Stimulation",
        "trip_data": {
            "title": "The Spice Coast Uncharted",
            "destination": "Wayanad and Coorg",
            "country": "India",
            "duration_days": 6,
            "best_season": "October to February",
            "summary": "Mist-covered coffee estates, tribal forest trails, and waterfalls that appear on no map. The Western Ghats hold a version of India most travellers never find — raw, fragrant, and completely alive.",
            "days": [
                {"day": 1, "location": "Wayanad", "theme": "Arrival in Green", "activities": ["Check into a coffee estate homestay", "Evening walk through cardamom plantation", "Bonfire dinner with estate family"], "accommodation": "Coffee plantation homestay", "food": "Kerala sadya on banana leaf"},
                {"day": 2, "location": "Chembra Peak", "theme": "Summit", "activities": ["Trek to Chembra Peak 2100m", "Heart-shaped lake at the summit", "Spot Nilgiri langurs on descent"], "accommodation": "Estate homestay", "food": "Puttu and kadala curry breakfast"},
                {"day": 3, "location": "Edakkal Caves", "theme": "Ancient", "activities": ["Edakkal cave Neolithic carvings", "Phantom Rock viewpoint", "Ambalavayal tribal heritage museum"], "accommodation": "Forest edge resort", "food": "Bamboo biryani at tribal cooperative"},
                {"day": 4, "location": "Coorg", "theme": "Coffee and Mist", "activities": ["Abbey Falls sunrise visit before tourists arrive", "Coffee roasting experience at Raja's Seat estate", "Dubare elephant camp interaction"], "accommodation": "Coorg bungalow estate", "food": "Pandi curry Kodava pork dish"},
                {"day": 5, "location": "Talakaveri", "theme": "Source", "activities": ["Trek to Brahmagiri peak", "Source of Kaveri river ritual bath", "Bhagamandala confluence temple"], "accommodation": "Madikeri heritage guesthouse", "food": "Kadambuttu with mutton curry"},
                {"day": 6, "location": "Departure", "theme": "Last Trail", "activities": ["Early morning bird watching", "Buy estate coffee and spices", "Depart to Mysore or Bangalore"], "accommodation": "Transit", "food": "Mangalore buns and filter coffee"}
            ],
            "packing_tips": ["Carry insect repellent for forest trails", "Lightweight rain jacket even in dry season", "Trekking shoes essential for Chembra", "Carry enough cash as ATMs are sparse"],
            "estimated_budget": "₹25,000 - ₹40,000 per person excluding flights"
        }
    },

    # ── Group 2: Restoration & Wellness ──
    {
        "intent": "Digital Detox",
        "intent_group": "Restoration & Wellness",
        "trip_data": {
            "title": "The Silence Between Mountains",
            "destination": "Spiti Valley",
            "country": "India",
            "duration_days": 7,
            "best_season": "May to October",
            "summary": "No mobile signal. No crowds. Just 4000-metre cold desert, ancient Buddhist monasteries, and the kind of silence that makes you realise how loud your life has been. Spiti Valley is not a destination — it is a reset.",
            "days": [
                {"day": 1, "location": "Shimla to Narkanda", "theme": "Detachment", "activities": ["Last internet use — intentional digital goodbye", "Drive through apple orchards", "Hatu Peak short hike"], "accommodation": "Narkanda guesthouse", "food": "Himachali dham meal"},
                {"day": 2, "location": "Rampur to Spiti Entry", "theme": "Transition", "activities": ["Drive along Sutlej gorge", "Enter Kinnaur district", "Sangla Valley meadow walk"], "accommodation": "Sangla homestay", "food": "Siddu steamed bread with ghee"},
                {"day": 3, "location": "Kalpa", "theme": "Kinner Kailash", "activities": ["View Kinner Kailash peak at sunrise", "Ancient Kalpa monastery visit", "Village walk with local guide"], "accommodation": "Kalpa orchard homestay", "food": "Trout fish curry from local river"},
                {"day": 4, "location": "Tabo", "theme": "Ancient Wisdom", "activities": ["Tabo monastery 10th century frescoes", "Cave meditation room visit", "Sunset meditation on monastery roof with monk"], "accommodation": "Tabo monastery guesthouse", "food": "Simple monastery dal rice"},
                {"day": 5, "location": "Kaza", "theme": "Cold Desert", "activities": ["Key Monastery 11th century fortress", "Kibber village highest motorable village walk", "Chicham bridge highest bridge in Asia"], "accommodation": "Kaza eco-lodge", "food": "Thupka and butter tea"},
                {"day": 6, "location": "Chandratal Lake", "theme": "The Moon Lake", "activities": ["Trek to Chandratal Lake", "Camp beside the lake at 4300m", "Milky Way photography — zero light pollution"], "accommodation": "Lakeside tent camp", "food": "Camp fire dinner under stars"},
                {"day": 7, "location": "Return", "theme": "Carry the Silence", "activities": ["Final morning meditation", "Drive back through Rohtang", "Arrive Manali"], "accommodation": "Manali hotel", "food": "Manali cafe meal as re-entry to civilisation"}
            ],
            "packing_tips": ["No phone signal from Day 2 onwards — prepare offline entertainment", "Carry physical books and a journal", "Warm layers even in summer — nights hit minus 5", "Download offline maps before entering Kinnaur"],
            "estimated_budget": "₹30,000 - ₹50,000 per person excluding flights to Shimla"
        }
    },
    {
        "intent": "Rejuvenation",
        "intent_group": "Restoration & Wellness",
        "trip_data": {
            "title": "Backwaters and Breath",
            "destination": "Alleppey and Varkala",
            "country": "India",
            "duration_days": 6,
            "best_season": "November to February",
            "summary": "A houseboat drifting through palm-fringed canals, sunrise yoga on a cliff above the Arabian Sea, and Ayurvedic treatments so deep they reach muscles you forgot you had. Kerala does not just relax you — it dissolves you.",
            "days": [
                {"day": 1, "location": "Alleppey", "theme": "Arrival on Water", "activities": ["Board private houseboat at noon", "Drift through village canals", "Sunset from boat deck with coconut water"], "accommodation": "Premium houseboat with AC", "food": "Kerala fish curry and karimeen on boat"},
                {"day": 2, "location": "Alleppey Backwaters", "theme": "Stillness", "activities": ["Morning canoe through narrow village canals", "Visit local coir weaving workshop", "Afternoon nap as boat moves — no schedule"], "accommodation": "Houseboat night 2", "food": "Appam and stew breakfast on deck"},
                {"day": 3, "location": "Varkala", "theme": "The Cliff", "activities": ["Check into cliff-top yoga retreat", "Evening Hatha yoga class", "Sunset on Varkala beach below the cliff"], "accommodation": "Yoga retreat cliff cottage", "food": "Seafood at cliff-side restaurant"},
                {"day": 4, "location": "Varkala", "theme": "Ayurveda", "activities": ["Full day Panchakarma Ayurvedic treatment", "Shirodhara oil therapy", "Evening pranayama session"], "accommodation": "Yoga retreat", "food": "Sattvic Ayurvedic meal — no spice no oil"},
                {"day": 5, "location": "Kappil Beach", "theme": "Solitude", "activities": ["Private beach with no tourists", "Kayak through Kappil Lake estuary", "Sunset meditation on empty beach"], "accommodation": "Varkala heritage villa", "food": "Toddy and fresh catch at local shack"},
                {"day": 6, "location": "Departure", "theme": "Take It With You", "activities": ["Final sunrise yoga", "Buy Ayurvedic oils to continue at home", "Depart Thiruvananthapuram"], "accommodation": "Transit", "food": "Sadhya breakfast before flight"}
            ],
            "packing_tips": ["Loose cotton clothing for Ayurvedic treatments", "Avoid synthetic fabrics in Kerala heat", "Book houseboat minimum 4 weeks in advance", "Sunscreen SPF 50 for cliff and beach days"],
            "estimated_budget": "₹35,000 - ₹60,000 per person excluding flights to Kochi"
        }
    },

    # ── Group 3: Connection & Kinship ──
    {
        "intent": "Family Bonding",
        "intent_group": "Connection & Kinship",
        "trip_data": {
            "title": "Rajasthan by Royal Rail",
            "destination": "Jaipur, Jodhpur, and Udaipur",
            "country": "India",
            "duration_days": 8,
            "best_season": "October to March",
            "summary": "Forts that took centuries to build, camels at sunset over golden sand, and a lake palace that floats on water like a dream. Rajasthan is the kind of place that makes every age group in the family feel like they are living inside a story.",
            "days": [
                {"day": 1, "location": "Jaipur", "theme": "The Pink City", "activities": ["Amber Fort elephant ride at sunrise", "City Palace family tour", "Jantar Mantar astronomical wonder for kids"], "accommodation": "Heritage haveli hotel", "food": "Dal baati churma Rajasthani thali"},
                {"day": 2, "location": "Jaipur", "theme": "Bazaars", "activities": ["Hawa Mahal photo stop", "Johari Bazaar gemstone shopping", "Block printing workshop for kids and adults"], "accommodation": "Heritage haveli hotel", "food": "Laal maas mutton curry at Niro's"},
                {"day": 3, "location": "Pushkar", "theme": "Sacred Lake", "activities": ["Pushkar Lake sunrise ritual", "Camel ride on Pushkar dunes", "Rose garden walking tour"], "accommodation": "Pushkar lake view hotel", "food": "Pure vegetarian thali — Pushkar is meat-free"},
                {"day": 4, "location": "Jodhpur", "theme": "The Blue City", "activities": ["Mehrangarh Fort — largest in India", "Blue city rooftop walk", "Flying Fox zipline over the fort for adventurous family members"], "accommodation": "Jodhpur fort view hotel", "food": "Mirchi bada and makhaniya lassi"},
                {"day": 5, "location": "Jaisalmer", "theme": "Desert", "activities": ["Sam Sand Dunes camel safari", "Overnight desert camp with cultural performance", "Sunrise over dunes — unmissable"], "accommodation": "Luxury desert camp", "food": "Ker sangri desert bean curry at camp"},
                {"day": 6, "location": "Jaisalmer", "theme": "Living Fort", "activities": ["Jaisalmer Fort — people still live inside", "Patwon Ki Haveli carving tour", "Bada Bagh cenotaphs sunset"], "accommodation": "Fort view heritage hotel", "food": "5 course Rajasthani royal dinner"},
                {"day": 7, "location": "Udaipur", "theme": "Lakes", "activities": ["City Palace lake view tour", "Boat ride to Lake Palace hotel", "Bagore Ki Haveli evening dance performance"], "accommodation": "Lake Pichola view hotel", "food": "Dinner on rooftop with lake view"},
                {"day": 8, "location": "Departure", "theme": "Royal Exit", "activities": ["Saheliyon Ki Bari garden morning walk", "Last shopping for miniature paintings", "Depart from Udaipur airport"], "accommodation": "Transit", "food": "Mawa kachori farewell breakfast"}
            ],
            "packing_tips": ["Comfortable walking shoes for fort cobblestones", "Dupattas and scarves for temple entry", "Carry ORS sachets for desert days", "Book desert camp minimum 2 weeks ahead"],
            "estimated_budget": "₹55,000 - ₹90,000 per person excluding flights"
        }
    },
    {
        "intent": "Romantic Escape",
        "intent_group": "Connection & Kinship",
        "trip_data": {
            "title": "Where the Flowers Never Stop",
            "destination": "Sikkim and Darjeeling",
            "country": "India",
            "duration_days": 7,
            "best_season": "March to May and October to November",
            "summary": "Rhododendron forests blazing in red, a toy train winding through clouds, and Kanchenjunga appearing at dawn like a private revelation. The Eastern Himalayas have a tenderness to them that makes romance feel inevitable.",
            "days": [
                {"day": 1, "location": "Gangtok", "theme": "Arrival in Clouds", "activities": ["MG Road evening walk hand in hand", "Enchey Monastery twilight visit", "Flower market sunrise next morning"], "accommodation": "Boutique hotel with Kanchenjunga view", "food": "Gyathuk noodle soup for two"},
                {"day": 2, "location": "Tsomgo Lake", "theme": "Frozen Mirror", "activities": ["Tsomgo Lake at 12310 ft", "Yak ride together at the lake", "Baba Mandir sacred stop"], "accommodation": "Gangtok boutique hotel", "food": "Sikkimese set meal with local millet beer tongba"},
                {"day": 3, "location": "Pelling", "theme": "The Hanging Bridge", "activities": ["Skywalk glass bridge over valley", "Kanchenjunga sunrise from Sangachoeling Monastery", "Khecheopalri Lake sacred forest walk"], "accommodation": "Pelling mountain view resort", "food": "Churpi cheese and buckwheat pancakes"},
                {"day": 4, "location": "Yuksom", "theme": "First Capital", "activities": ["Trekking through ancient coronation site", "Dubdi Monastery oldest in Sikkim", "Picnic by Kathok Lake in rhododendron forest"], "accommodation": "Heritage guesthouse Yuksom", "food": "Homemade gundruk soup at homestay"},
                {"day": 5, "location": "Darjeeling", "theme": "Toy Train", "activities": ["Sunrise at Tiger Hill — Kanchenjunga and Everest visible", "Darjeeling Himalayan Railway joyride", "Tea estate tour and first flush tasting"], "accommodation": "Colonial era Windamere Hotel", "food": "High tea with Darjeeling first flush"},
                {"day": 6, "location": "Darjeeling", "theme": "Colonial Romance", "activities": ["Batasia Loop garden sunrise", "Japanese Peace Pagoda walk", "Sunset at Observatory Hill temple"], "accommodation": "Windamere Hotel", "food": "Candlelit dinner at Glenary's restaurant"},
                {"day": 7, "location": "Departure", "theme": "Last Sunrise", "activities": ["Final tea garden morning walk", "Buy personal blended tea as memory", "Depart to Bagdogra airport"], "accommodation": "Transit", "food": "Momos and chai farewell breakfast"}
            ],
            "packing_tips": ["Inner line permit required for some Sikkim areas — arrange in advance", "Warm layers even in spring", "Carry a small bag for day treks", "Book Windamere Hotel well in advance — only 25 rooms"],
            "estimated_budget": "₹40,000 - ₹65,000 per person excluding flights to Bagdogra"
        }
    },

    # ── Group 4: Tactical & Pragmatic ──
    {
        "intent": "The Quick Break",
        "intent_group": "Tactical & Pragmatic",
        "trip_data": {
            "title": "48 Hours in the Queen of Hills",
            "destination": "Ooty and Coonoor",
            "country": "India",
            "duration_days": 3,
            "best_season": "October to June",
            "summary": "A long weekend that feels like a week. The Nilgiri Mountain Railway, eucalyptus forests that smell like another planet, and tea so fresh it tastes like it was picked that morning — because it was. Ooty is the proof that the best escapes do not need to be far.",
            "days": [
                {"day": 1, "location": "Ooty", "theme": "Arrive and Breathe", "activities": ["Nilgiri Mountain Railway ride from Mettupalayam", "Botanical Garden afternoon walk", "Ooty Lake sunset rowboat"], "accommodation": "Colonial bungalow hotel", "food": "Home-style Nilgiri lamb stew"},
                {"day": 2, "location": "Coonoor", "theme": "Tea and Trails", "activities": ["Highfield Tea Estate sunrise tour and tasting", "Sim's Park flower garden", "Dolphin's Nose viewpoint trek"], "accommodation": "Tea estate heritage bungalow", "food": "Colonial high tea with fresh scones at estate"},
                {"day": 3, "location": "Departure", "theme": "Take the Slow Train Home", "activities": ["Doddabetta Peak sunrise — highest in Nilgiris", "Toda tribal village visit", "Return on mountain railway"], "accommodation": "Transit", "food": "Varkey and jam breakfast before departure"}
            ],
            "packing_tips": ["Light woolens for evenings", "Walking shoes for garden trails", "Book mountain railway tickets online in advance", "Carry a reusable bag for fresh tea purchases"],
            "estimated_budget": "₹12,000 - ₹22,000 per person excluding travel to Mettupalayam"
        }
    },
    {
        "intent": "Wanderlust",
        "intent_group": "Tactical & Pragmatic",
        "trip_data": {
            "title": "The Living Root Bridges",
            "destination": "Meghalaya",
            "country": "India",
            "duration_days": 6,
            "best_season": "October to April",
            "summary": "Bridges grown from living tree roots over 500 years. The wettest place on Earth where villages float in mist. Meghalaya is the only place in India where nature has been building infrastructure longer than humans have — and doing it better.",
            "days": [
                {"day": 1, "location": "Shillong", "theme": "Scotland of the East", "activities": ["Ward's Lake morning walk", "Don Bosco museum — Northeast India culture", "Police Bazaar evening street food"], "accommodation": "Shillong heritage guesthouse", "food": "Jadoh red rice and pork Khasi staple"},
                {"day": 2, "location": "Cherrapunji", "theme": "Wettest Place", "activities": ["Nohkalikai Falls — highest plunge waterfall India", "Mawsmai Cave limestone adventure", "Seven Sisters Falls viewpoint"], "accommodation": "Cherrapunji eco-resort", "food": "Tungrymbai fermented soybean with pork"},
                {"day": 3, "location": "Nongriat", "theme": "The Living Bridge", "activities": ["Trek to Double Decker Living Root Bridge 3500 steps", "Swim in crystal blue Rainbow Falls", "Return trek by lantern after sunset"], "accommodation": "Nongriat village homestay", "food": "Village family dinner — whatever they cook"},
                {"day": 4, "location": "Mawlynnong", "theme": "Cleanest Village", "activities": ["Mawlynnong — Asia's cleanest village walk", "Living root bridge in the village", "Sky view bamboo platform over Bangladesh border"], "accommodation": "Bamboo cottage homestay", "food": "Organic village meal cooked on wood fire"},
                {"day": 5, "location": "Dawki", "theme": "Invisible Water", "activities": ["Umngot River boat ride — so clear boat appears to float on air", "Bangladesh border view", "Shnongpdeng cliff jumping optional"], "accommodation": "River camp Dawki", "food": "Fish fresh from Umngot river"},
                {"day": 6, "location": "Departure", "theme": "Carry the Mist", "activities": ["Early morning Shillong Peak panorama", "Shop for Meghalaya honey and bamboo crafts", "Depart from Shillong"], "accommodation": "Transit", "food": "Pukhlein rice jaggery snack for the road"}
            ],
            "packing_tips": ["Waterproof everything — even in dry season it can rain", "Trekking poles for Nongriat 3500 steps", "Carry cash — no ATMs in villages", "Permit required for areas near Bangladesh border"],
            "estimated_budget": "₹28,000 - ₹45,000 per person excluding flights to Guwahati"
        }
    }
]

# ─────────────────────────────────────────────
# SAMPLE REVIEWS PER TRIP
# ─────────────────────────────────────────────

SAMPLE_REVIEWS = [
    {"reviewer_name": "Arjun M.", "rating": 5, "comment": "Completely transformed how I think about travel. The AI found exactly what I needed without me having to explain it twice."},
    {"reviewer_name": "Priya S.", "rating": 5, "comment": "Every single recommendation was spot on. Places I never would have found on my own. Already planning my next trip."},
    {"reviewer_name": "Rahul K.", "rating": 4, "comment": "The itinerary was incredibly detailed and realistic. The food suggestions alone were worth it."},
    {"reviewer_name": "Sneha R.", "rating": 5, "comment": "I said I wanted a break and it gave me exactly that — not a tourist checklist but an actual experience."},
    {"reviewer_name": "Vikram T.", "rating": 4, "comment": "Planned a family trip with three kids and it nailed the pace. No one was bored, no one was exhausted."},
]


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r'[\s_]+', '-', text)
    text = re.sub(r'[^a-z0-9-]', '', text)
    text = text.strip('-')
    text = re.sub(r'-+', '-', text)
    return text


def generate_unique_slug(title: str) -> str:
    base_slug = slugify(title)
    result = supabase.table("trips").select("slug").eq("slug", base_slug).execute()
    if len(result.data) == 0:
        return base_slug
    short_id = str(uuid.uuid4())[:8]
    return f"{base_slug}-{short_id}"


def insert_trip(trip_config: dict) -> str | None:
    trip_data = trip_config["trip_data"]
    slug = generate_unique_slug(trip_data["title"])

    print(f"\n→ Inserting: {trip_data['title']} ({slug})")

    # Generate image keywords
    print(f"  Generating image keywords...")
    try:
        image_keywords = run_image_agent(trip_data)
        print(f"  Card keyword: {image_keywords.get('card')}")
    except Exception as e:
        print(f"  Image agent failed: {e}. Using fallback.")
        image_keywords = {
            "hero": [f"{trip_data['destination']} India landscape"],
            "days": [f"{trip_data['destination']} India"] * len(trip_data["days"]),
            "card": f"{trip_data['destination']} India",
            "intent_mood": trip_config["intent"].lower()
        }

    insert_data = {
        "slug": slug,
        "user_id": None,
        "title": trip_data["title"],
        "destination": trip_data["destination"],
        "country": trip_data["country"],
        "duration_days": trip_data["duration_days"],
        "best_season": trip_data["best_season"],
        "summary": trip_data["summary"],
        "intent": trip_config["intent"],
        "intent_group": trip_config["intent_group"],
        "trip_data": trip_data,
        "image_keywords": image_keywords,
        "is_public": True
    }

    result = supabase.table("trips").insert(insert_data).execute()

    if not result.data:
        print(f"  FAILED to insert trip")
        return None

    trip_id = result.data[0]["id"]
    print(f"  Inserted with ID: {trip_id}")
    return trip_id


def insert_reviews(trip_id: str, destination: str):
    print(f"  Inserting {len(SAMPLE_REVIEWS)} reviews...")
    reviews = []
    for review in SAMPLE_REVIEWS:
        reviews.append({
            "trip_id": trip_id,
            "reviewer_name": review["reviewer_name"],
            "rating": review["rating"],
            "comment": review["comment"],
            "trip_image_keyword": destination.split()[0].lower(),
            "is_approved": True
        })

    result = supabase.table("reviews").insert(reviews).execute()
    print(f"  Inserted {len(result.data)} reviews")


def main():
    print("=" * 50)
    print("TravellerHero Demo Trip Seeder")
    print("=" * 50)
    print(f"Inserting {len(DEMO_TRIPS)} trips with reviews...")

    success_count = 0

    for trip_config in DEMO_TRIPS:
        trip_id = insert_trip(trip_config)
        if trip_id:
            insert_reviews(trip_id, trip_config["trip_data"]["destination"])
            success_count += 1
        # Small delay between LLM calls
        time.sleep(2)

    print("\n" + "=" * 50)
    print(f"Done. {success_count}/{len(DEMO_TRIPS)} trips inserted successfully.")
    print("=" * 50)


if __name__ == "__main__":
    main()
